Rack Attack - Throttle 10requests / second
OpenSourcePolitics/decidim-app pull request #157
Opened 2022-09-13 14:12 UTC by Quentinchampenois

#### Description

Rack Attack seems to be very restrictive with the current configuration => 100 req / 100 secs

2022-09-13 14:14 UTC, Quentinchampenois commented
Should we store Rack attack logs outside `production.log` ? Maybe in `rack_attack.log`

2022-09-13 15:05 UTC, paulinebessoles approved these changes

2022-09-13 15:49 UTC, moustachu requested changes
I don't know if it was your assumption but 100 req / 100 sec is not the same as 1 req / 1 s. 
A single user should not make 100 request in 1m40s on a platform like Decidim, he is supposed to read some stuff between the pages and actions. 

Anyway, even if we want to change those parameters, we should : 
- change directly the value of `Decidim.throttling_max_requests` and `Decidim.throttling_max_requests`
- Use environment variables to make those changes

2022-09-14 12:37 UTC, paulinebessoles approved these changes

2022-09-19 12:56 UTC, armandfardeau approved these changes

2022-09-19 12:58 UTC, moustachu approved these changes

2022-09-19 13:01 UTC, merged