Fix/rack attack configuration
OpenSourcePolitics/decidim-app pull request #164
Opened 2022-09-26 19:36 UTC by Quentinchampenois

#### Description

Update Rack attack configuration, aim is to cleanup the log files generated and have a better overview

#### Tasks

- [x] Update throttle rules
- [x] Apply rails secrets for configuration
- [x] Allow to disable Rack::Attack
- [x] Add specs
- [x] Create a custom 429 Error page 
- [ ] Configure Allow2Ban
 
#### Screenshots
<img width="700" alt="Screenshot 2022-09-26 at 21 08 14" src="https://user-images.githubusercontent.com/26109239/192364179-497834e7-393e-4277-a81e-bd6877b9247d.png">

2022-09-27 08:00 UTC, moustachu requested changes
We should remove the original throttle configuration from decidim-core.
https://github.com/OpenSourcePolitics/decidim-app/blob/fix/rack-attack-double-throttle/config/initializers/rack_attack.rb#L6

_It's not possible to overwrite an existing configuration with a "throttle block", you need to remove it directly from the configuration hash_

2022-09-27 08:00 UTC, moustachu commented on config/initializers/rack_attack.rb
> +  <!-- This file lives in public/422.html -->
remove HTML comment :wink:

2022-09-27 08:00 UTC, moustachu commented on config/initializers/rack_attack.rb
> +  req.ip unless req.path.start_with?("/assets") || req.path.start_with?("/rails/active_storage")
Change `/assets` path to `/decidim-packs`

2022-09-27 08:00 UTC, moustachu commented on config/initializers/rack_attack.rb
> +  until_period = I18n.l(Time.zone.at(now + 60), format: :decidim_short)
Use `match_data[:period]` instead of hard coded value `60`

2022-11-14 14:23 UTC, armandfardeau approved these changes

2022-11-14 15:23 UTC, moustachu approved these changes

2022-11-15 09:58 UTC, paulinebessoles approved these changes

2022-11-15 09:58 UTC, merged