Make available locales configurable
OpenSourcePolitics/decidim-app pull request #188
Opened 2022-11-15 16:40 UTC by armandfardeau

2022-11-15 17:06 UTC, paulinebessoles reviewed
Awesome feature! The only problem I have in locale is that when I switch locale, I arrive on an error with the following URL: http://localhost:3000/locale?locale=fr
For example, when I'm on the sign up page in french, and I want to switch locale for es, I'm redirected on this URL: http://localhost:3000/locale?locale=es

2022-11-15 17:08 UTC, paulinebessoles commented
Also, what happens if we remove a locale from the env variables with a production DB?

2022-11-16 10:05 UTC, paulinebessoles approved these changes

2022-11-16 10:15 UTC, moustachu requested changes
@armandfardeau This need to have a default value in case de env var is missing 😉

2022-11-16 16:39 UTC, moustachu approved these changes

2022-11-16 16:39 UTC, merged