Fix survey validation
OpenSourcePolitics/decidim-app pull request #228
Opened 2023-01-19 21:17 UTC by eliegaboriau

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-01-20 15:00 UTC, paulinebessoles submitted a review, later dismissed
Thank you @eliegaboriau 👏

2023-01-20 15:23 UTC, paulinebessoles submitted a review, later dismissed

2023-01-20 15:59 UTC, Quentinchampenois requested changes
Thanks for the fix, product tests work as expected

I think we should limit overrides and use extends. Also can you add entries of added overrides to the OVERLOADS.md file please ?

2023-01-20 15:59 UTC, Quentinchampenois commented on app/cells/decidim/forms/step_navigation_cell.rb
> +      def errors
We should implement this method in an extend

2023-01-20 15:59 UTC, Quentinchampenois commented on app/helpers/decidim/forms/application_helper.rb
> +        bool = false
```suggestion
                responses.map { |res| res.errors.any? }.any?
```

You can return an array of bool and just check if one of them is true

2023-01-20 17:23 UTC, paulinebessoles submitted a review, later dismissed

2023-01-23 08:51 UTC, moustachu approved these changes

2023-01-23 14:04 UTC, Quentinchampenois approved these changes

2023-01-23 14:05 UTC, merged