[Fix] Uploaded images in newsletter
OpenSourcePolitics/decidim-app pull request #270
Opened 2023-03-02 15:17 UTC by Quentinchampenois

This reverts commit c8ea32deb905b72cf873c643d511d167988bef2b.

#### :tophat: Description
*Please describe your pull request.*

I revert again to add again the fix of the newsletter image uploader

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to c8ea32deb905b72cf873c643d511d167988bef2b

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to newsletter
* Upload image
* See full path in src attribute of img HTML tag

Test is available on vinland.osp.dev (check letter_opener for checking image)

#### Information

I had to revert my PR because it causes a crash on start of production application (cd44), however I can't reproduce on decidim-app

2023-03-02 17:19 UTC, armandfardeau approved these changes

2023-03-03 11:08 UTC, moustachu approved these changes

2023-03-03 14:28 UTC, OuardaOUBAHRI requested changes
Hello @Quentinchampenois ! the fix works perfectly on production. But on development , I have problem with all the images, can you fix that too ? Thank you

2023-03-06 10:00 UTC, armandfardeau submitted a review, later dismissed
LGTM ! Waiting for @OuardaOUBAHRI review to merge.

2023-03-06 14:12 UTC, OuardaOUBAHRI approved these changes

2023-03-06 14:20 UTC, merged