Clean gemfile and run bundle install
OpenSourcePolitics/decidim-app pull request #274
Opened 2023-03-16 15:08 UTC by paulinebessoles

#### :tophat: Description
Make gems more visibles so we can see clearly which Decidim and Decidim external modules are deployed. 

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-03-31 12:24 UTC, armandfardeau submitted a review, later dismissed

2023-04-06 09:04 UTC, Quentinchampenois requested changes
As discussed, PR aims to bump to Decidim v0.26.5 however version doesn't change in Gemfile.lock

2023-04-06 09:04 UTC, paulinebessoles commented
I still have some work to do on this PR, some things seems to have fail!

2023-04-06 09:05 UTC, Quentinchampenois commented
> I still have some work to do on this PR, some things seems to have fail!

Please pull before or rebase this branch because I just merged conflict in Gemfile.lock !

2023-04-14 13:10 UTC, armandfardeau submitted a review, later dismissed

2023-04-18 09:09 UTC, eliegaboriau approved these changes
LGTM, you should may use the DECIDIM BRANCH for ludens too

2023-04-18 09:09 UTC, eliegaboriau commented on Gemfile
> +gem "decidim-ludens", git: "https://github.com/OpenSourcePolitics/decidim-ludens.git", branch: "release/0.26-stable"
```suggestion
gem "decidim-ludens", git: "https://github.com/OpenSourcePolitics/decidim-ludens.git", branch: DECIDIM_BRANCH
```

2023-04-19 12:17 UTC, eliegaboriau approved these changes

2023-04-20 08:08 UTC, Quentinchampenois approved these changes
LGTM  !

2023-04-20 08:13 UTC, merged