Pin sidekiq
OpenSourcePolitics/decidim-app pull request #291
Opened 2023-04-25 11:52 UTC by armandfardeau

#### :tophat: Description
Pin sidekiq

#### :pushpin: Related Issues
- [Notion card](https://www.notion.so/opensourcepolitics/CESE-Sidekiq-mail-7ae4e69ddb864b2db596d80911290100?pvs=4)

2023-04-26 12:22 UTC, Quentinchampenois approved these changes

2023-04-26 12:22 UTC, Quentinchampenois requested changes
"sidekiq-scheduler" dependency should also be pinned

2023-04-27 10:34 UTC, Quentinchampenois approved these changes

2023-04-27 10:56 UTC, eliegaboriau approved these changes

2023-04-27 11:09 UTC, merged