Bump interactive maps (#300)
OpenSourcePolitics/decidim-app pull request #301
Opened 2023-05-02 16:09 UTC by paulinebessoles

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md
- [ ] In case of new dependencies or version bump, update related documentation

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-05-02 18:12 UTC, armandfardeau requested changes
Thanks for your contribution!

2023-05-02 18:12 UTC, armandfardeau commented on Gemfile.lock
> +   2.4.6
```suggestion
   2.4.9
```

2023-05-03 14:24 UTC, armandfardeau approved these changes

2023-05-03 15:34 UTC, Quentinchampenois approved these changes

2023-05-03 15:35 UTC, merged