feat: improve k8s rake
OpenSourcePolitics/decidim-app pull request #338
Opened 2023-06-29 09:18 UTC by pierreozoux

#### :tophat: Description
Dans les grandes lignes:
Je n'avais pas besoin du sync, je vais le faire en ansible.

Il me fallait un secret spécifique pour la SECRET_KEY_BASE, l'opérateur attends cela.
Et J'ai changé les quelques nom d'objets ci et là, pour correspondre aux attentes de l'opérateur.

#### Testing
```
ssh mako@decidim-migration-dry-run -p 124
cd decidim-app
bundle exec rails k8s:export_configuration IMAGE="rg.fr-par.scw.cloud/decidim-app/decidim-app:develop"
```

Le hostname de cette instance de test est:
```
decidim-migration-dry-run.osp.dev
```
(Et donc les ressources sont nommées sur le sous domaine.)

L'output est:

Le contenu du bucket est bien dans:
```
tmp/k8s-migration/decidim-migration-dry-run/buckets/decidim-migration-dry-run--de/
```

Et le dump pg dans:
```
tmp/k8s-migration/decidim-migration-dry-run/postgres/decidim-migration-dry-run--de.dump
```

tmp/k8s-migration/decidim-migration-dry-run/application.yml
```bash
---
apiVersion: apps.libre.sh/v1alpha1
kind: Decidim
metadata:
  name: decidim-migration-dry-run
spec:
  image: rg.fr-par.scw.cloud/decidim-app/decidim-app:develop
  host: decidim-migration-dry-run.osp.dev
  additionalHosts: []
  organization:
    id: 1
  locale:
    default: en
    available:
    - fr
    - en
  usersRegistrationMode: 0
  forceUsersToAuthenticateBeforeAccessOrganization: false
  availableAuthorizations:
  - id_documents
  - postal_letter
  - csv_census
  - phone_authorization_handler
  - osp_authorization_handler
  fileUploadSettings:
    maximum_file_size:
      avatar: 5
      default: 10
    allowed_content_types:
      admin:
      - image/*
      - application/vnd.oasis.opendocument
      - application/vnd.ms-*
      - application/msword
      - application/vnd.ms-word
      - application/vnd.openxmlformats-officedocument
      - application/vnd.oasis.opendocument
      - application/pdf
      - application/rtf
      - text/plain
      default:
      - image/*
      - application/pdf
      - application/rtf
      - text/plain
    allowed_file_extensions:
      admin:
      - jpg
      - jpeg
      - gif
      - png
      - bmp
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - ppx
      - rtf
      - txt
      - odt
      - ott
      - odf
      - otg
      - ods
      - ots
      image:
      - jpg
      - jpeg
      - gif
      - png
      - bmp
      - ico
      default:
      - jpg
      - jpeg
      - gif
      - png
      - bmp
      - pdf
      - rtf
      - txt
  timeZone: UTC
  envFrom:
  - secretRef:
      name: decidim-migration-dry-run-custom-env
```

tmp/k8s-migration/decidim-migration-dry-run/manifests/decidim-migration-dry-run--de.yml
```bash
---
apiVersion: v1
kind: Secret
metadata:
  name: decidim-migration-dry-run--de
stringData:
  SECRET_KEY_BASE: xxx
```

tmp/k8s-migration/decidim-migration-dry-run/manifests/decidim-migration-dry-run-custom-env.yml
```bash
---
apiVersion: v1
kind: Secret
metadata:
  name: decidim-migration-dry-run-custom-env
stringData:
  THROTTLING_MAX_REQUESTS: '100'
  THROTTLING_PERIOD: '1'
  ENABLE_RACK_ATTACK: '1'
  RACK_ATTACK_FAIL2BAN: '1'
  SENTRY_SIDEKIQ_SAMPLE_RATE: '0.1'
  SENTRY_SAMPLE_RATE: '0.5'
  FRIENDLY_SIGNUP_OVERRIDE_PASSWORDS: '1'
  FRIENDLY_SIGNUP_INSTANT_VALIDATION: '1'
  FRIENDLY_SIGNUP_HIDE_NICKNAME: '1'
  FRIENDLY_SIGNUP_USE_CONFIRMATION_CODES: '1'
  ENABLE_LETTER_OPENER: '0'
  SMTP_FROM: arnulfo <ginette@mcglynn.name>
  SMTP_PORT: '25'
  SMTP_ADDRESS: decidim-migration-dry-run.osp.dev
  SMTP_USER_NAME: darwin_brown
  SMTP_FROM_EMAIL: ginette@mcglynn.name
  SMTP_FROM_LABEL: arnulfo
  SMTP_PASSWORD: xxx
```

2023-06-29 09:28 UTC, hrenard commented
Ok pour moi.
Je pense que ça serait bien d'aussi ajouter l'admin instance et l'admin orga pour éviter de faire un autre script pour le moment où on activera la fonctionnalité dans l'operator.

2023-06-29 10:50 UTC, moustachu requested changes

2023-06-29 10:50 UTC, moustachu commented on lib/k8s_organization_exporter.rb
> +      stringData: @env_vars.merge!(smtp_settings).merge!(omniauth_settings).to_json
`env_vars` plutôt que `@env_vars` pour forcer le 1er appel et charger la variable

2023-06-29 13:59 UTC, pierreozoux commented on lib/k8s_organization_exporter.rb
> +      stringData: @env_vars.merge!(smtp_settings).merge!(omniauth_settings).to_json
```suggestion
      stringData: env_vars.merge!(smtp_settings).merge!(omniauth_settings).to_json
```

2023-06-29 14:53 UTC, armandfardeau reviewed
The CI didn't run because it is triggered only by push (a mistake),

I'm checking the tests and fixing it

2023-06-29 15:59 UTC, hrenard commented
Le secret xxx-custom-env.yml est mal formaté. `.stringData` a une string à la place d'un objet.

2023-06-29 16:14 UTC, armandfardeau requested changes

2023-06-29 16:14 UTC, armandfardeau commented on lib/k8s_organization_exporter.rb
>      @bucket_name ||= env_vars["SCALEWAY_BUCKET_NAME"]
D'où vient cette variable qui est supprimée?

2023-07-03 07:57 UTC, pierreozoux commented on lib/k8s_organization_exporter.rb
>      @bucket_name ||= env_vars["SCALEWAY_BUCKET_NAME"]
Dans la première version du script, Alain utilisait organization_slug, mais j'en ai pas besoin.

2023-07-03 16:48 UTC, moustachu approved these changes

2023-07-04 08:04 UTC, merged