[Fix] - Notifications not sending from importing answers of proposals
OpenSourcePolitics/decidim-app pull request #441
Opened 2023-09-29 08:58 UTC by AyakorK

#### :tophat: Description
We observed that when importing proposals, certain notifications were not being sent to the user after a proposal had been responded to. This PR has been created to address this issue.

#### :pushpin: Related Issues
- Related to [Decidim#10728](https://github.com/decidim/decidim/pull/10728/files)

#### Testing
*Describe the best way to test or validate your PR.*

* Log in as user
* Enable notifications by email in Real Time
* Follow three proposals
* As administrator
* Import answers to the previous proposals
* User should receive email in letter opener
* User and Admin should receive in-app notification

#### Tasks
- [ ] Extend the function that causes the issue
- [ ] Add specs

2023-09-29 09:35 UTC, Quentinchampenois requested changes
Thanks for the PR !

I have some changes to address.
I just wonder what is the email received when `NotifyProposalAnswer` receive an empty string as second parameter ?

2023-09-29 09:35 UTC, Quentinchampenois commented on spec/lib/decidim/proposals/import/proposal_answer_creator_spec.rb
> +        before do
```suggestion
        let!(:proposal) { create(:proposal, component: component, state: nil) }
```

2023-09-29 09:35 UTC, Quentinchampenois commented on spec/lib/decidim/proposals/import/proposal_answer_creator_spec.rb
> +          it "notifies followers" do
Duplicate of line :120  
Please define a new shared_example "notifies followers"

2023-09-29 09:40 UTC, AyakorK commented
> Thanks for the PR !
> 
> I have some changes to address. I just wonder what is the email received when `NotifyProposalAnswer` receive an empty string as second parameter ?

In response to your question, the current manual process already interprets the "not_answered" statement as an empty string, so it essentially duplicates it.

Regarding the upcoming changes, I look forward to them! Thank you!

2023-09-29 13:11 UTC, Quentinchampenois approved these changes
Thanks !

2023-10-02 10:34 UTC, luciegrau approved these changes
LGTM, thank you Guillaume for the quick fix!

2023-10-02 10:34 UTC, merged