[ADD] Documentation
OpenSourcePolitics/decidim-app pull request #45
Opened 2022-01-07 09:45 UTC by Quentinchampenois

Add missing documentation : License, contributing, security guide

2022-01-07 10:02 UTC, armandfardeau approved these changes

2022-01-07 10:12 UTC, moustachu requested changes

2022-01-07 10:12 UTC, moustachu commented on docs/SECURITY.md
> +* armand [at] opensourcepolitics [dot] eu
change to security@opensourcepolitics.eu

2022-01-11 12:56 UTC, armandfardeau approved these changes

2022-01-14 14:22 UTC, merged