[Fix] - Single Initiative Type Blocked the edit form
OpenSourcePolitics/decidim-app pull request #471
Opened 2024-01-04 10:00 UTC by AyakorK

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Notion card](https://www.notion.so/opensourcepolitics/Bordeaux-Cannot-change-initiative-type-d94e823ac9614593bbbad18985a447af?pvs=4)

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Create an Initiative Type
* Create an Initiative with the type previously created
* Go back to BackOffice
* Try to edit it
* Check that everything works correctly
* Now go into your db and delete every initiatives type except the one you created previously
* Check that everything still works correctly

#### Tasks
- [x] Add specs
- [x] Edit form to hide if there is only one single initiative type but still retrieve infos

2024-01-08 12:53 UTC, Quentinchampenois requested changes

2024-01-08 12:53 UTC, Quentinchampenois commented on app/views/decidim/initiatives/admin/initiatives/_form.html.erb
> +                          {
Hash argument isn't needed for a `hidden_field` field

2024-01-11 12:48 UTC, Quentinchampenois approved these changes

2024-01-11 15:47 UTC, luciegrau approved these changes
LGTM, thank you!

2024-01-11 15:47 UTC, merged