Fix/parent scope filter
OpenSourcePolitics/decidim-app pull request #550
Opened 2024-05-30 14:58 UTC by Stef-Rousset

#### :tophat: Description
In an assembly on proposals index view, sometimes  in the filters, a scope is not checked because its children are not checked while they should be all checked when loading the page.

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=1988f63b9b3e4cb6abd1e2b4bcbc53cc&pm=c)

#### Testing
*Describe the best way to test or validate your PR.*

1. As an admin, create an assembly with scopes enabled, choose a scope that has subscopes (like "Indiana"), or choose one assembly that has scopes enabled and a scope.
2. As an admin, go to parameters > scopes > Indiana, click on one of its subscopes (like [Grimesstad) and  add subscopes to it
3. As a user, go to the assemblies > assembly > proposals and see in the filters that all the scopes and their children are checked

#### Tasks
- [X ] Add specs

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2024-05-30 17:08 UTC, BarbaraOliveira13 submitted a review, later dismissed
Ran it, works 👍 👏

2024-06-03 13:32 UTC, Quentinchampenois requested changes
Hey ! It works well, I tested with 4 levels of subscopes and it is already checked as expected ! 

I just have a refactor suggestion to reduce the level of indentation and perceived complexity

2024-06-03 13:32 UTC, Quentinchampenois commented on lib/extends/controllers/decidim/proposals/proposals_controller_extends.rb
> +    def default_filter_scope_params
```suggestion
        def default_filter_scope_params
      return "all" unless current_component.scopes.any?

      scope = current_component.scope
      return current_component_scope_ids if scope.blank?

      subscope_ids = scope.children&.map(&:id)
      ids = ["all", scope.id] + subscope_ids
      ids += Decidim::Scope.where(parent_id: subscope_ids).pluck(:id) if subscope_ids.present?
      ids.map(&:to_s)
    end

    def current_component_scope_ids
      component_scopes = current_component.scopes.pluck(:id).map(&:to_s)

      %w(all global) + component_scopes
    end
```

2024-06-03 13:32 UTC, Quentinchampenois commented on lib/extends/controllers/decidim/proposals/proposals_controller_extends.rb
> +    def default_filter_scope_params
This a refactor suggestion, it works the same way you did

2024-06-04 16:37 UTC, merged