Backport initiatives exports pdf
OpenSourcePolitics/decidim-app pull request #562
Opened 2024-06-19 13:58 UTC by Stef-Rousset

#### :tophat: Description
Currently all the initiatives signatures PDF file have always the columns "Name and surname", "Document number" and "Date of birth". This doesn't make much sense as this should depend if the Intiative Type has the " Collect participant personal data on signature " setting enabled.

This PR takes into account this setting to show these columns in the export PDF file.

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card](https://www.notion.so/opensourcepolitics/bd4bf860eab94f9daca7da803f09e3b2?v=c96df65755dd403d95e86f82d7749709&p=016bfb32d01f4373be6c0c53bb6ce6e5&pm=c)

#### Testing
1. As an admin, go to http://localhost:3000/admin/initiatives
2. Then, click in "Edit' (pencil) of an initiative, check which Initiative type this Initiative has. Go to that Initiative type and check that " Collect participant personal data on signature " setting is not checked.
3. Click in the "Export PDF of signatures" button. See that you don't have the columns "Name and surname, Date of birth, document number, postal code"
4. Go back to Initiative type and edit it to enable the " Collect participant personal data on signature " setting. 
5. Export the PDF again and see that you have those columns.

### :camera: Screenshots
Pdf with Collect participant personal data on signature not checked => 
<img width="1003" alt="Capture d’écran 2024-06-19 à 15 55 30" src="https://github.com/OpenSourcePolitics/decidim-app/assets/61418966/f6f39456-a7b2-49fc-8e17-4aec139019e7">

Pdf with Collect participant personal data on signature checked =>
<img width="1006" alt="Capture d’écran 2024-06-19 à 15 54 30" src="https://github.com/OpenSourcePolitics/decidim-app/assets/61418966/3cd68438-ea42-427b-b67e-dce91c0cd57f">

2024-06-19 14:19 UTC, Quentinchampenois requested changes
There is a failing spec on locales

Otherwise it is good to me !

2024-06-19 14:48 UTC, luciegrau reviewed
Tested locally, works great! Thanks!

2024-06-19 14:49 UTC, luciegrau submitted a review, later dismissed

2024-06-20 07:26 UTC, Stef-Rousset commented
Specs are corrected, thanks @Quentinchampenois

2024-06-21 14:30 UTC, BarbaraOliveira13 approved these changes
I ran it, works 🎉

2024-06-21 14:48 UTC, luciegrau approved these changes

2024-06-24 08:22 UTC, Quentinchampenois approved these changes

2024-06-24 08:22 UTC, merged