feat: Add Sendethics possibility to the sms gateway
OpenSourcePolitics/decidim-app pull request #605
Opened 2024-10-09 12:28 UTC by AyakorK

#### :tophat: Description
This adds the possibility of sending messages through Sendethics api which has a different behaviour from previous providers like ÉtoileDièse or Twilio

#### :pushpin: Related Issues
*Link your PR to an issue*
- [Decidim-app - Ajout SMS Gateway with Sendethics](https://opensourcepolitics.odoo.com/web?db=opensourcepolitics&signup_email=guillaume%40opensourcepolitics.eu&token=ixqNZ9S5lGRCj9ADpsQq#id=2579&cids=1&menu_id=325&action=471&model=project.task&view_type=form)

#### Testing
*Describe the best way to test or validate your PR.*

### Creation of the Instance

- Create a .env
- Fill in those data (Please note that you can test both of Sendethics or [Twilio, EtoileDièse] depending what you need to test there
```
# SENDETHICS 
SMS_GATEWAY_MB_API_KEY=<your_api_key>
SMS_GATEWAY_MB_ACCOUNT_ID=<your_account_id>

# ETOILEDIESE OR TWILIO
SMS_GATEWAY_USERNAME=<username_on_provider>
SMS_GATEWAY_PASSWORD=<password_on_provider>

# GLOBAL ENV VARS
SMS_GATEWAY_SERVICE="Decidim::SmsGatewayService" # Mandatory to be this one
SMS_GATEWAY_URL="<url_to_use>" # Please make sure this does not end with a "/" otherwise it will cause errors
```
- Setup your app

#### 🚨 If you have to change your .env you'll need to restart your app to apply changes !

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* Go to authentication settings
* Enable authentication using SMS
* Go to participatory processes
* Access participatory process 
* Access settings from a budget component
* Make sure you can vote without the zipcode (otherwise won't work)
* Go to front office
* Access the budget and try to vote
* Fill in your phone number and try to send the SMS
* Make sure you receive the message on your phone 

#### Tasks
- [x] Add specs
- [x] Add env vars
- [x] Modify the service to add the behavior from Sendethics

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2024-10-17 18:31 UTC, Quentinchampenois requested changes
I will continue this PR

2024-10-17 18:31 UTC, Quentinchampenois commented on app/services/decidim/sms_gateway_service.rb
> +      if @url.include?("services.message-business.com")
Prefer to define a dedicated class implementing an interface SmsGateway with method `request` callable rather than if / else condition

2024-11-07 09:59 UTC, moustachu approved these changes
Refactor later 🕐

2024-11-07 10:00 UTC, luciegrau approved these changes

2024-11-07 11:42 UTC, merged