Fix/missing image in survey question
OpenSourcePolitics/decidim-app pull request #621
Opened 2024-11-05 16:37 UTC by Stef-Rousset

#### :tophat: Description
When adding an image without text in a question's description of a survey, the image is visible in the description after save, and when you save again, the image is still present.

#### :pushpin: Related Issues
- [Notion card](https://www.notion.so/opensourcepolitics/Rillieux-Decidim-app-Probl-me-avec-l-ajout-des-photos-dans-la-partie-description-des-questions-d-0cdc0b986018457e95f5de547ecddc8b)

#### Testing

1. As an admin, got to a survey.
2. Add a question and drag and drop an image in the description of the question (do not add text in description)
3. Save
4. See that the image is displayed in the description
5. Modify the title of the question and save again
6. See that the image is still displayed in the description

#### Tasks
- [X ] Add specs

2024-11-07 09:23 UTC, luciegrau requested changes
Hello Stephanie, thank you for the PR! 🚀 
I just tested it locally and I have a feedback: when I add an image to a question description without text, **the image is well displayed in the BO but it's not in the preview of the survey.** 
Nevertheless, the image is well displayed to front office users, so it's not a big problem, but ideally administrators should be able to preview the survey before publishing it with the images they want to include in the descriptions. 

Here are a few screenshots to illustrate my feedback: 

**As an admin, the image is displayed in BO in my question description:** 
<img width="1050" alt="Capture d’écran 2024-11-07 à 10 17 00" src="https://github.com/user-attachments/assets/4f2e8fb3-77c2-4cdd-b894-2700d44db3fd">

**As an admin, when I click on the button to preview my survey, the image is not displayed in the preview.**
<img width="885" alt="Capture d’écran 2024-11-07 à 10 20 19" src="https://github.com/user-attachments/assets/f141944a-8901-4567-9a1f-78be7c693977">

**As a user, when the survey is published in FO, I can see the image displayed in the description:** 
<img width="684" alt="Capture d’écran 2024-11-07 à 10 22 24" src="https://github.com/user-attachments/assets/dd907703-0173-42b6-bcbc-2c5c1f7202f9">

Are you experiencing the same behaviour?

2024-11-07 10:00 UTC, Stef-Rousset commented
Hello Lucie,

I just tested in local and I have the image in the preview. When you go to the preview, are you in the same language that in BO ? Sometimes you had the image in french, and when you go to the front the language is english and you don't see the picture...

2024-11-07 10:10 UTC, luciegrau commented
Hi Steph, thanks for the product explanation, you're quite right it was the language selected 😅. I was able to re-test and the image appears correctly in the preview when the language selected in FO is the same as the one in which the image was uploaded. 
All good for the product recipe for this PR then, I approve thank you! 🥳

2024-11-07 10:11 UTC, luciegrau approved these changes

2024-11-13 13:53 UTC, Quentinchampenois commented
> **As a user, when the survey is published in FO, I can see the image displayed in the description:** <img alt="Capture d’écran 2024-11-07 à 10 22 24" width="684" src="https://private-user-images.githubusercontent.com/87868063/383894548-dd907703-0173-42b6-bcbc-2c5c1f7202f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDYwMzQsIm5iZiI6MTczMTUwNTczNCwicGF0aCI6Ii84Nzg2ODA2My8zODM4OTQ1NDgtZGQ5MDc3MDMtMDE3My00MmI2LWJjYmMtMmM1YzFmNzIwMmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEzNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZGM4NjFhNzlmNGU4M2U1MzI0NmUzMzQ5MDU0ZTEyMDAxZDIwMjZhZTViYmJjYzgzY2U1ZDdkZWUwZmY4NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EATA-xWQPgPSg7PQF8dYoBqbdk0tTs02F1hM7CJ0orM">

✌️✌️✌️ 👒

2024-11-13 13:54 UTC, Quentinchampenois approved these changes

2024-11-13 13:58 UTC, merged