Env define asset host 0.25
OpenSourcePolitics/decidim-app pull request #78
Opened 2022-03-21 16:04 UTC by Quentinchampenois

2022-03-21 16:10 UTC, eliegaboriau approved these changes

2022-03-21 16:50 UTC, paulinebessoles requested changes

2022-03-21 16:50 UTC, paulinebessoles commented on config/application.rb
> +    config.asset_host = "https://#{Rails.application.secrets[:asset_host]}/" if Rails.application.secrets[:asset_host].present?
```suggestion
    config.action_mailer.asset_host = "https://#{Rails.application.secrets[:asset_host]}/" if Rails.application.secrets[:asset_host].present?
```

2022-03-21 16:55 UTC, paulinebessoles commented on config/application.rb
> +    config.asset_host = "https://#{Rails.application.secrets[:asset_host]}/" if Rails.application.secrets[:asset_host].present?
Hi @Quentinchampenois I spotted this little problem, I propose to change it here and I already did it on the develop branch https://github.com/OpenSourcePolitics/decidim-app/commit/a14ddb99fe3ce4d2779f007377bbfb6d899d7138

2022-03-22 16:56 UTC, paulinebessoles approved these changes

2022-03-22 16:57 UTC, merged